<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('id','changepassword-form');
$form->setAttribute('class','form-horizontal');
?>				

<h2><?php echo $this->translate("Change your password"); ?></h2>

<hr/>

<?php echo $this->form()->openTag($form); ?>


	<div class="form-group">
    	<label class="col-lg-4 control-label input-lg"><?php echo $this->translate("Current password"); ?></label>
    	<div class="col-lg-6">
    	<?php echo $this->formRow($form->get('password')); ?>
    	</div>
  	</div>

	<div class="form-group">
    	<label class="col-lg-4 control-label input-lg"><?php echo $this->translate("New password"); ?></label>
    	<div class="col-lg-6">
    	<?php echo $this->formRow($form->get('new_password1')); ?>
    	</div>
  	</div>
  	
	<div class="form-group">
    	<label class="col-lg-4 control-label input-lg"><?php echo $this->translate("Confirm password"); ?></label>
    	<div class="col-lg-6">
    	<?php echo $this->formRow($form->get('new_password2')); ?>
    	</div>
  	</div>
  	
  	
  	<div class="form-group">
    	<div class="col-lg-offset-4 col-lg-6">
			<button type="submit" class="btn btn-success btn-lg"><?php echo $this->translate("Change Password"); ?></button>
		</div>
	</div>

<?php echo $this->form()->closeTag(); ?>
