<?php
$form = $this->form;

$form->prepare();
$form->setAttribute('id','passwordrecovery-form');
$form->setAttribute('class','form-horizontal');
$this->form($form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL );

?>
	
<h2><?php echo $this->translate("Password recovery"); ?></h2>

<hr/>

<div>
	<h3><?php echo $this->translate('How does it works?'); ?></h3>
	
	<p><?php echo $this->translate('A new secure password will be generated. An email will be sent to you with new password credential.'); ?></p>
	<p><?php echo sprintf( '%s <a href="%s">%s</a>', $this->translate('Use the received password in the login form.'), $this->url('login-user-login'), $this->translate("Go to login form") ); ?></p>
	<p><?php echo $this->translate('We do not hold your password becasue it is encrypted on system so we have no access to it.'); ?></p>
	<p><?php echo $this->translate('Remember to store your new password in a cool, dry place (but not the fridge) out of direct sunlight and away from heat, sparks and flames!'); ?></p>	
</div>

<?php echo $this->form()->openTag($form); ?>
		
	<?php echo $this->formRow($form->get('email')); ?>
  	
  	<div class="form-group">
    	<div class="col-lg-offset-3 col-lg-6">
			<button type="submit" class="btn btn-success btn-lg"><?php echo $this->translate("Recover you password"); ?></button>
		</div>
	</div>
  	  		
	<!--<?php echo $this->formSubmit($form->get('submit')); ?>-->

<?php echo $this->form()->closeTag();
