<div class="row">



<div class="col-md-4">

	<h3><?php echo $this->translate('Keep you data safe'); ?></h3>
	
	<p><?php echo $this->translate('Your data is safe beacause of our regular backup and redundat data. You will never lose a single bit'); ?></p>
	
	<h3><?php echo $this->translate('Access from anywhere'); ?></h3>
	
	<p><?php echo $this->translate('You can access the application from anywhere and from any browser.'); ?></p>
	
	<h3><?php echo $this->translate('Direct invoice send'); ?></h3>
	
	<p><?php echo $this->translate('You can send your invoice directly to customer using send-by-mail function wich means no more download to your computer and complex procedures. A link is provided in the invoices list and a single click let you send your invoice.'); ?></p>
		
</div>

<div class="col-md-8">
<h2><?php echo $this->translate('Sign up'); ?></h2>

<hr/>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('id','register-form');
$this->form($form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL );
?>			

<?php echo $this->form()->openTag($form); ?>
		
	<?php echo $this->formRow($form->get('login')); ?>
	<?php echo $this->formRow($form->get('password')); ?> 
	<?php echo $this->formRow($form->get('password2')); ?> 

	<hr/>

	<?php echo $this->formRow($form->get('name')); ?>
	<?php echo $this->formRow($form->get('vat')); ?>	
	<?php echo $this->formRow($form->get('address')); ?>
	<?php echo $this->formRow($form->get('zip')); ?>
	<?php echo $this->formRow($form->get('city')); ?>

		
  	<div class="form-group">
    	<div class="col-lg-offset-4 col-lg-8">
			<button type="submit" class="btn btn-success btn-lg"><?php echo $this->translate("Register"); ?></button>
		</div>
	</div>
  	  		
	<!--<?php echo $this->formSubmit($form->get('submit')); ?>-->

<?php echo $this->form()->closeTag(); ?>

</div>
</div>